# Generated by Django 6.0.5 on 2026-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='seguimientos/')),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=20, unique=True)),
                ('origen', models.TextField()),
                ('destino', models.TextField()),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('en_progreso', 'En progreso'), ('terminado', 'Terminado')], default='sin_asignar', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
