# Generated by Django 6.0.5 on 2026-05-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
        ('usuarios', '0002_empresa_alter_usuario_options_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='sede',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
