# Generated by Django 6.0.5 on 2026-05-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_novedad_options_alter_seguimiento_options_and_more'),
        ('usuarios', '0002_empresa_alter_usuario_options_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.empresa'),
        ),
    ]
