# Generated by Django 6.0.5 on 2026-05-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_destino_lat_servicio_destino_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ciudad_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_pago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_entrega_deseada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_quien_recibe',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_solicitante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicio',
            name='telefono_quien_recibe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicio',
            name='telefono_solicitante',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_recorrido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
