# Generated by Django 6.0.5 on 2026-06-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_servicio_ciudad_destino_servicio_ciudad_origen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['paso'], 'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='paso',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('en_progreso', 'En progreso'), ('terminado', 'Terminado')], db_index=True, default='sin_asignar', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='orden',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
