# Generated by Django 6.0.5 on 2026-06-04 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_seguimiento_options_alter_seguimiento_paso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='paso',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UbicacionMensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Ubicación de Mensajero',
                'verbose_name_plural': 'Ubicaciones de Mensajeros',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['servicio', '-timestamp'], name='servicios_u_servici_0e1e5e_idx'), models.Index(fields=['mensajero', '-timestamp'], name='servicios_u_mensaje_62ca57_idx')],
            },
        ),
    ]
