# Generated by Django 6.0.5 on 2026-06-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_seguimiento_options_alter_seguimiento_paso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionmensajero',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ubicacionmensajero',
            name='servicios_u_servici_0e1e5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ubicacionmensajero',
            name='servicios_u_mensaje_62ca57_idx',
        ),
        migrations.RenameField(
            model_name='ubicacionmensajero',
            old_name='lat',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='ubicacionmensajero',
            old_name='lng',
            new_name='longitud',
        ),
        migrations.AddField(
            model_name='servicio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ubicacionmensajero',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmensajero',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_tiempo_real', to='servicios.servicio'),
        ),
        migrations.RemoveField(
            model_name='ubicacionmensajero',
            name='mensajero',
        ),
        migrations.RemoveField(
            model_name='ubicacionmensajero',
            name='timestamp',
        ),
    ]
