# Generated by Django 6.0.5 on 2026-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_alter_usuario_options_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('coordinador', 'Coordinador'), ('cliente', 'Cliente'), ('mensajero', 'Mensajero'), ('registro_coordinador', 'Registro Coordinador')], max_length=25),
        ),
    ]
